-- Flag questions that were generated by MindScan (AI) so the host can
-- visually distinguish them from manually-typed or JSON-imported questions.
alter table public.questions
  add column if not exists ai_generated boolean not null default false;

comment on column public.questions.ai_generated is
  'true when this question was generated by MindScan; false for manual or JSON-imported questions.';
